# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StripeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StripeApp

  target 'StripeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'StripeApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StripeApp-tvOS

  target 'StripeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
